# Generated by Django 4.2.17 on 2024-12-18 14:00

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clusters',
            fields=[
                ('CustomerName', models.CharField(max_length=128)),
                ('OndiskOver', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.98'), max_digits=3, null=True)),
                ('NumDG', models.IntegerField()),
                ('NumCapDisks', models.IntegerField()),
                ('SSDSize', models.IntegerField()),
                ('NumNodes', models.IntegerField()),
                ('FTM', models.FloatField(choices=[(1.0, 'PFTT0'), (0.5, 'PFTT1'), (0.333, 'PFTT2'), (0.25, 'PFTT3'), (0.75, 'FTM5-PFTT1'), (0.67, 'FTM6-PFTT2')])),
                ('Clusterid', models.AutoField(primary_key=True, serialize=False)),
                ('RawCap', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('SpbmCap', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
